# spring ?? profile? local? ??. (???? default)
spring:
  profiles:
    active: local

# local profile? ????.
---
spring:
  profiles:
    default: local
  h2:
    console:
      enabled: true # h2 ?????? H2 ?????? ??? ??? ? ?? ??.
      path: /h2-console # ????? ????.

  datasource:
    url: jdbc:h2:tcp://localhost/~/tennsi-store
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create # ?????? ?? ??? ???? drop?? ?? ????.
    properties:
      hibernate:
        format_sql: true # sql ??? ?? ? ?????.

logging:
  level:
    org.hibernate.SQL: debug # logger? ?? ?????? ?? SQL? ???.